### ISSUE TITLE
Change the balloon background

### ISSUE THREAD

**Issue by VoyTechnology** [SeanHealy33/Redbrick-Turns-20#10]
I am not exactly sure to what, but the image is unbearable

**Comment by SeanHealy33** [comment]
It was never going to be in the final. It was just the first thing I found when I looked up balloon background

**Comment by SeanHealy33** [comment]
@CianLR Will be making the background that will be used in place of the balloons :+1:

**Comment by GoldenBadger** [comment]
@VoyTechnology Misspelled "balloon" in title. @SeanHealy33 Don't fix this until he changes it :P

**Comment by SeanHealy33** [comment]
I know you all loved the balloons but I decided to get rid of them :( 
d74b1c0
